### PR TITLE
Bump build number

### PR DESCRIPTION
**Pull request by brainstorm**
As per issue https://github.com/conda-forge/staged-recipes/pull/3435#issuecomment-322226540

### CODE REVIEW

**Comment by jakirkham** [comment]
Please submit this from your fork in the future, @brainstorm. Otherwise it will deploy as soon as the CIs pass (i.e. before merging).

**Comment by brainstorm** [comment]
Didn't I do precisely that this time, @jakirkham?:

skarmavbild 2017-08-14 kl 20 32 32

**Comment by jakirkham** [comment]
Though it seems this branch was pushed to the feedstock as well. Hence the extra CI builds.

**Comment by brainstorm** [comment]
TravisCI failed with `binstar_client.errors.Unauthorized: ('Authorization token is no longer valid', 401)` ... what am I doing wrong here, @jakirkham ? :-S

**Comment by jakirkham** [comment]
This is more fallout from having pushed this branch to the feedstock. Please merge and delete the additional branch from the feedstock. Thanks.

**Comment by jakirkham** [comment]
Turns out there is another issue too as this has an expired token (happened in the past few days). Am readding it to `staged-recipes` to fix that. Sorry for the trouble.

xref: https://github.com/conda-forge/staged-recipes/pull/3591

**Pull request merged**
