### PR TITLE
Trigger CI build since initial feedstock import failed

### PR DESCRIPTION
**Pull request by brainstorm**
Add url_doc as well.

### CODE REVIEW

**Comment by isuruf** [comment]
Please use PRs from forks.

**Comment by jakirkham** [comment]
Strange that none of the CIs built on the first pass. 😕

**Comment by brainstorm** [comment]
@isuruf Sorry about that, I'll fork and PR from my repo next time... may I ask why, btw?
@jakirkham Puzzled as well, it was all green on staged-recipes and then, no conda uploads when it went to feedstocks, bizarre.

**Comment by isuruf** [comment]
When forks are not used, each commit is built twice. (One for branch and one for PR) Also, when forks are not used, the built package is uploaded immediately before the PR is merged because there is a CI job for the branch.

**Pull request merged**
